// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlTO6hWtU3r2gCvCZLeRTvrh2fFCPRhlo',
    appId: '1:296028833875:web:498b72bf6faff5569edea6',
    messagingSenderId: '296028833875',
    projectId: 'volt-987e9',
    authDomain: 'volt-987e9.firebaseapp.com',
    storageBucket: 'volt-987e9.firebasestorage.app',
    measurementId: 'G-1EP0MREHXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq9YjEqiGJS5TD5vtEdB-OClRIe3v9OY8',
    appId: '1:296028833875:android:b5b219ee18354b409edea6',
    messagingSenderId: '296028833875',
    projectId: 'volt-987e9',
    storageBucket: 'volt-987e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_kQJT6qPwfrjOMlPbxKB9YFtpVO2yK8',
    appId: '1:296028833875:ios:fccc9f0472904c5e9edea6',
    messagingSenderId: '296028833875',
    projectId: 'volt-987e9',
    storageBucket: 'volt-987e9.firebasestorage.app',
    iosBundleId: 'com.example.volt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_kQJT6qPwfrjOMlPbxKB9YFtpVO2yK8',
    appId: '1:296028833875:ios:fccc9f0472904c5e9edea6',
    messagingSenderId: '296028833875',
    projectId: 'volt-987e9',
    storageBucket: 'volt-987e9.firebasestorage.app',
    iosBundleId: 'com.example.volt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlTO6hWtU3r2gCvCZLeRTvrh2fFCPRhlo',
    appId: '1:296028833875:web:6c920afaae123d599edea6',
    messagingSenderId: '296028833875',
    projectId: 'volt-987e9',
    authDomain: 'volt-987e9.firebaseapp.com',
    storageBucket: 'volt-987e9.firebasestorage.app',
    measurementId: 'G-NXQT64F7YY',
  );
}
